// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-07-23T09:32:50.558Z

export const __CANONICAL_MODULE_NAME = "users";
