/*
 * Open Game Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Backend.Client.OpenAPIDateConverter;

namespace Backend.Model.Lobbies
{
    /// <summary>
    /// JoinRequest
    /// </summary>
    [DataContract(Name = "lobbies__join__Request")]
    public partial class JoinRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JoinRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected JoinRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="JoinRequest" /> class.
        /// </summary>
        /// <param name="lobbyId">lobbyId (required).</param>
        /// <param name="players">players (required).</param>
        /// <param name="noWait">noWait.</param>
        public JoinRequest(string lobbyId = default(string), List<Object> players = default(List<Object>), bool noWait = default(bool))
        {
            // to ensure "lobbyId" is required (not null)
            if (lobbyId == null)
            {
                throw new ArgumentNullException("lobbyId is a required property for JoinRequest and cannot be null");
            }
            this.LobbyId = lobbyId;
            // to ensure "players" is required (not null)
            if (players == null)
            {
                throw new ArgumentNullException("players is a required property for JoinRequest and cannot be null");
            }
            this.Players = players;
            this.NoWait = noWait;
        }

        /// <summary>
        /// Gets or Sets LobbyId
        /// </summary>
        [DataMember(Name = "lobbyId", IsRequired = true, EmitDefaultValue = true)]
        public string LobbyId { get; set; }

        /// <summary>
        /// Gets or Sets Players
        /// </summary>
        [DataMember(Name = "players", IsRequired = true, EmitDefaultValue = true)]
        public List<Object> Players { get; set; }

        /// <summary>
        /// Gets or Sets NoWait
        /// </summary>
        [DataMember(Name = "noWait", EmitDefaultValue = true)]
        public bool NoWait { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JoinRequest {\n");
            sb.Append("  LobbyId: ").Append(LobbyId).Append("\n");
            sb.Append("  Players: ").Append(Players).Append("\n");
            sb.Append("  NoWait: ").Append(NoWait).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
