/*
 * Open Game Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Backend.Client.OpenAPIDateConverter;

namespace Backend.Model.Lobbies
{
    /// <summary>
    /// CreateResponseLobbyBackendServerPortsValueRouting
    /// </summary>
    [DataContract(Name = "lobbies__create__Response_lobby_backend_server_ports_value_routing")]
    public partial class CreateResponseLobbyBackendServerPortsValueRouting
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateResponseLobbyBackendServerPortsValueRouting" /> class.
        /// </summary>
        /// <param name="gameGuard">gameGuard.</param>
        /// <param name="host">host.</param>
        public CreateResponseLobbyBackendServerPortsValueRouting(Object gameGuard = default(Object), Object host = default(Object))
        {
            this.GameGuard = gameGuard;
            this.Host = host;
        }

        /// <summary>
        /// Gets or Sets GameGuard
        /// </summary>
        [DataMember(Name = "game_guard", EmitDefaultValue = false)]
        public Object GameGuard { get; set; }

        /// <summary>
        /// Gets or Sets Host
        /// </summary>
        [DataMember(Name = "host", EmitDefaultValue = false)]
        public Object Host { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateResponseLobbyBackendServerPortsValueRouting {\n");
            sb.Append("  GameGuard: ").Append(GameGuard).Append("\n");
            sb.Append("  Host: ").Append(Host).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
