/*
 * Open Game Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Backend.Client.OpenAPIDateConverter;

namespace Backend.Model.Lobbies
{
    /// <summary>
    /// CreateResponseLobbyBackendLocalDevelopment
    /// </summary>
    [DataContract(Name = "lobbies__create__Response_lobby_backend_localDevelopment")]
    public partial class CreateResponseLobbyBackendLocalDevelopment
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateResponseLobbyBackendLocalDevelopment" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateResponseLobbyBackendLocalDevelopment() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateResponseLobbyBackendLocalDevelopment" /> class.
        /// </summary>
        /// <param name="ports">ports (required).</param>
        public CreateResponseLobbyBackendLocalDevelopment(Dictionary<string, CreateResponseLobbyBackendLocalDevelopmentPortsValue> ports = default(Dictionary<string, CreateResponseLobbyBackendLocalDevelopmentPortsValue>))
        {
            // to ensure "ports" is required (not null)
            if (ports == null)
            {
                throw new ArgumentNullException("ports is a required property for CreateResponseLobbyBackendLocalDevelopment and cannot be null");
            }
            this.Ports = ports;
        }

        /// <summary>
        /// Gets or Sets Ports
        /// </summary>
        [DataMember(Name = "ports", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, CreateResponseLobbyBackendLocalDevelopmentPortsValue> Ports { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateResponseLobbyBackendLocalDevelopment {\n");
            sb.Append("  Ports: ").Append(Ports).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
