/*
 * Open Game Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Backend.Client.OpenAPIDateConverter;

namespace Backend.Model.Lobbies
{
    /// <summary>
    /// FindOrCreateRequestCreateConfig
    /// </summary>
    [DataContract(Name = "lobbies__find_or_create__Request_createConfig")]
    public partial class FindOrCreateRequestCreateConfig
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FindOrCreateRequestCreateConfig" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FindOrCreateRequestCreateConfig() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FindOrCreateRequestCreateConfig" /> class.
        /// </summary>
        /// <param name="region">region (required).</param>
        /// <param name="tags">tags.</param>
        /// <param name="maxPlayers">maxPlayers (required).</param>
        /// <param name="maxPlayersDirect">maxPlayersDirect (required).</param>
        public FindOrCreateRequestCreateConfig(string region = default(string), Dictionary<string, string> tags = default(Dictionary<string, string>), decimal maxPlayers = default(decimal), decimal maxPlayersDirect = default(decimal))
        {
            // to ensure "region" is required (not null)
            if (region == null)
            {
                throw new ArgumentNullException("region is a required property for FindOrCreateRequestCreateConfig and cannot be null");
            }
            this.Region = region;
            this.MaxPlayers = maxPlayers;
            this.MaxPlayersDirect = maxPlayersDirect;
            this.Tags = tags;
        }

        /// <summary>
        /// Gets or Sets Region
        /// </summary>
        [DataMember(Name = "region", IsRequired = true, EmitDefaultValue = true)]
        public string Region { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [DataMember(Name = "tags", EmitDefaultValue = false)]
        public Dictionary<string, string> Tags { get; set; }

        /// <summary>
        /// Gets or Sets MaxPlayers
        /// </summary>
        [DataMember(Name = "maxPlayers", IsRequired = true, EmitDefaultValue = true)]
        public decimal MaxPlayers { get; set; }

        /// <summary>
        /// Gets or Sets MaxPlayersDirect
        /// </summary>
        [DataMember(Name = "maxPlayersDirect", IsRequired = true, EmitDefaultValue = true)]
        public decimal MaxPlayersDirect { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FindOrCreateRequestCreateConfig {\n");
            sb.Append("  Region: ").Append(Region).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  MaxPlayers: ").Append(MaxPlayers).Append("\n");
            sb.Append("  MaxPlayersDirect: ").Append(MaxPlayersDirect).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
