/*
 * Open Game Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Backend.Client.OpenAPIDateConverter;

namespace Backend.Model.Lobbies
{
    /// <summary>
    /// SetPlayerDisconnectedRequest
    /// </summary>
    [DataContract(Name = "lobbies__set_player_disconnected__Request")]
    public partial class SetPlayerDisconnectedRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetPlayerDisconnectedRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SetPlayerDisconnectedRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SetPlayerDisconnectedRequest" /> class.
        /// </summary>
        /// <param name="lobbyId">lobbyId.</param>
        /// <param name="lobbyToken">lobbyToken.</param>
        /// <param name="playerTokens">playerTokens (required).</param>
        public SetPlayerDisconnectedRequest(string lobbyId = default(string), string lobbyToken = default(string), List<string> playerTokens = default(List<string>))
        {
            // to ensure "playerTokens" is required (not null)
            if (playerTokens == null)
            {
                throw new ArgumentNullException("playerTokens is a required property for SetPlayerDisconnectedRequest and cannot be null");
            }
            this.PlayerTokens = playerTokens;
            this.LobbyId = lobbyId;
            this.LobbyToken = lobbyToken;
        }

        /// <summary>
        /// Gets or Sets LobbyId
        /// </summary>
        [DataMember(Name = "lobbyId", EmitDefaultValue = false)]
        public string LobbyId { get; set; }

        /// <summary>
        /// Gets or Sets LobbyToken
        /// </summary>
        [DataMember(Name = "lobbyToken", EmitDefaultValue = false)]
        public string LobbyToken { get; set; }

        /// <summary>
        /// Gets or Sets PlayerTokens
        /// </summary>
        [DataMember(Name = "playerTokens", IsRequired = true, EmitDefaultValue = true)]
        public List<string> PlayerTokens { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SetPlayerDisconnectedRequest {\n");
            sb.Append("  LobbyId: ").Append(LobbyId).Append("\n");
            sb.Append("  LobbyToken: ").Append(LobbyToken).Append("\n");
            sb.Append("  PlayerTokens: ").Append(PlayerTokens).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
