/*
 * Open Game Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Backend.Client.OpenAPIDateConverter;

namespace Backend.Model.Lobbies
{
    /// <summary>
    /// CreateResponseLobbyBackend
    /// </summary>
    [DataContract(Name = "lobbies__create__Response_lobby_backend")]
    public partial class CreateResponseLobbyBackend
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateResponseLobbyBackend" /> class.
        /// </summary>
        /// <param name="test">test.</param>
        /// <param name="localDevelopment">localDevelopment.</param>
        /// <param name="server">server.</param>
        public CreateResponseLobbyBackend(Object test = default(Object), CreateResponseLobbyBackendLocalDevelopment localDevelopment = default(CreateResponseLobbyBackendLocalDevelopment), CreateResponseLobbyBackendServer server = default(CreateResponseLobbyBackendServer))
        {
            this.Test = test;
            this.LocalDevelopment = localDevelopment;
            this.Server = server;
        }

        /// <summary>
        /// Gets or Sets Test
        /// </summary>
        [DataMember(Name = "test", EmitDefaultValue = false)]
        public Object Test { get; set; }

        /// <summary>
        /// Gets or Sets LocalDevelopment
        /// </summary>
        [DataMember(Name = "localDevelopment", EmitDefaultValue = false)]
        public CreateResponseLobbyBackendLocalDevelopment LocalDevelopment { get; set; }

        /// <summary>
        /// Gets or Sets Server
        /// </summary>
        [DataMember(Name = "server", EmitDefaultValue = false)]
        public CreateResponseLobbyBackendServer Server { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateResponseLobbyBackend {\n");
            sb.Append("  Test: ").Append(Test).Append("\n");
            sb.Append("  LocalDevelopment: ").Append(LocalDevelopment).Append("\n");
            sb.Append("  Server: ").Append(Server).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
