/*
 * Open Game Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Backend.Client.OpenAPIDateConverter;

namespace Backend.Model.Lobbies
{
    /// <summary>
    /// DestroyRequest
    /// </summary>
    [DataContract(Name = "lobbies__destroy__Request")]
    public partial class DestroyRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DestroyRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DestroyRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DestroyRequest" /> class.
        /// </summary>
        /// <param name="lobbyId">lobbyId (required).</param>
        public DestroyRequest(string lobbyId = default(string))
        {
            // to ensure "lobbyId" is required (not null)
            if (lobbyId == null)
            {
                throw new ArgumentNullException("lobbyId is a required property for DestroyRequest and cannot be null");
            }
            this.LobbyId = lobbyId;
        }

        /// <summary>
        /// Gets or Sets LobbyId
        /// </summary>
        [DataMember(Name = "lobbyId", IsRequired = true, EmitDefaultValue = true)]
        public string LobbyId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DestroyRequest {\n");
            sb.Append("  LobbyId: ").Append(LobbyId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
