/*
 * Open Game Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Backend.Client.OpenAPIDateConverter;

namespace Backend.Model.Lobbies
{
    /// <summary>
    /// FindResponse
    /// </summary>
    [DataContract(Name = "lobbies__find__Response")]
    public partial class FindResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FindResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FindResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FindResponse" /> class.
        /// </summary>
        /// <param name="lobby">lobby (required).</param>
        /// <param name="players">players (required).</param>
        public FindResponse(CreateResponseLobby lobby = default(CreateResponseLobby), List<CreateResponsePlayersInner> players = default(List<CreateResponsePlayersInner>))
        {
            // to ensure "lobby" is required (not null)
            if (lobby == null)
            {
                throw new ArgumentNullException("lobby is a required property for FindResponse and cannot be null");
            }
            this.Lobby = lobby;
            // to ensure "players" is required (not null)
            if (players == null)
            {
                throw new ArgumentNullException("players is a required property for FindResponse and cannot be null");
            }
            this.Players = players;
        }

        /// <summary>
        /// Gets or Sets Lobby
        /// </summary>
        [DataMember(Name = "lobby", IsRequired = true, EmitDefaultValue = true)]
        public CreateResponseLobby Lobby { get; set; }

        /// <summary>
        /// Gets or Sets Players
        /// </summary>
        [DataMember(Name = "players", IsRequired = true, EmitDefaultValue = true)]
        public List<CreateResponsePlayersInner> Players { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FindResponse {\n");
            sb.Append("  Lobby: ").Append(Lobby).Append("\n");
            sb.Append("  Players: ").Append(Players).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
