/*
 * Open Game Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Backend.Client.OpenAPIDateConverter;

namespace Backend.Model.Users
{
    /// <summary>
    /// AuthenticateTokenResponse
    /// </summary>
    [DataContract(Name = "users__authenticate_token__Response")]
    public partial class AuthenticateTokenResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticateTokenResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AuthenticateTokenResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticateTokenResponse" /> class.
        /// </summary>
        /// <param name="userId">userId (required).</param>
        /// <param name="user">user.</param>
        public AuthenticateTokenResponse(string userId = default(string), FetchResponseUsersInner user = default(FetchResponseUsersInner))
        {
            // to ensure "userId" is required (not null)
            if (userId == null)
            {
                throw new ArgumentNullException("userId is a required property for AuthenticateTokenResponse and cannot be null");
            }
            this.UserId = userId;
            this.User = user;
        }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name = "userId", IsRequired = true, EmitDefaultValue = true)]
        public string UserId { get; set; }

        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [DataMember(Name = "user", EmitDefaultValue = false)]
        public FetchResponseUsersInner User { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthenticateTokenResponse {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
