// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-07-23T09:32:50.534Z

export const actorCaseConversionMap = {
	users: {},

	rateLimit: {
		limiter: ["rate_limit", "limiter"],
	},

	tokens: {},

	lobbies: {
		lobbyManager: ["lobbies", "lobby_manager"],
	},

	rivet: {},
} as const;
