// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-07-23T09:32:50.498Z

export type RequestOf<T> = T extends { request: any } ? T["request"] : never;
export type ResponseOf<T> = T extends { response: any } ? T["response"] : never;

export type ActorProxyLookupFn<ThisType> = <
	M extends keyof ActorsSnake & string,
	S extends keyof ActorsSnake[M] & string,
>(
	this: ThisType,
	module: M,
	script: S,
	req: RequestOf<ActorsSnake[M][S]>,
) => Promise<ResponseOf<ActorsSnake[M][S]>>;

//
// Types for users
//

interface Users_Module {
}

interface Users_ModuleCamel {
}

//
// Types for rate_limit
//

// modules.rateLimit.limiter
import type {
	Actor as RateLimit_Limiter_Actor,
} from "../../opengb-modules/modules/rate_limit/actors/limiter.ts";

interface RateLimit_Module {
	limiter: RateLimit_Limiter_Actor;
}

interface RateLimit_ModuleCamel {
	limiter: RateLimit_Limiter_Actor;
}

//
// Types for tokens
//

interface Tokens_Module {
}

interface Tokens_ModuleCamel {
}

//
// Types for lobbies
//

// modules.lobbies.lobbyManager
import type {
	Actor as Lobbies_LobbyManager_Actor,
} from "../../opengb-modules/modules/lobbies/actors/lobby_manager.ts";

interface Lobbies_Module {
	lobby_manager: Lobbies_LobbyManager_Actor;
}

interface Lobbies_ModuleCamel {
	lobbyManager: Lobbies_LobbyManager_Actor;
}

//
// Types for rivet
//

interface Rivet_Module {
}

interface Rivet_ModuleCamel {
}

interface ActorsSnake {
	users: Users_Module;
	rate_limit: RateLimit_Module;
	tokens: Tokens_Module;
	lobbies: Lobbies_Module;
	rivet: Rivet_Module;
}

interface ActorsCamel {
	users: Users_ModuleCamel;
	rateLimit: RateLimit_ModuleCamel;
	tokens: Tokens_ModuleCamel;
	lobbies: Lobbies_ModuleCamel;
	rivet: Rivet_ModuleCamel;
}
