// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-07-23T09:32:50.539Z

export const dependencyCaseConversionMap = {
	users: {
		fetch: ["users", "fetch"],
		create: ["users", "create"],
		authenticateToken: ["users", "authenticate_token"],
		createToken: ["users", "create_token"],
	},

	rateLimit: {
		throttle: ["rate_limit", "throttle"],
		throttlePublic: ["rate_limit", "throttle_public"],
	},

	tokens: {
		create: ["tokens", "create"],
		fetch: ["tokens", "fetch"],
		fetchByToken: ["tokens", "fetch_by_token"],
		revoke: ["tokens", "revoke"],
		validate: ["tokens", "validate"],
		extend: ["tokens", "extend"],
	},

	lobbies: {
		create: ["lobbies", "create"],
		destroy: ["lobbies", "destroy"],
		findOrCreate: ["lobbies", "find_or_create"],
		join: ["lobbies", "join"],
		list: ["lobbies", "list"],
		setLobbyReady: ["lobbies", "set_lobby_ready"],
		setPlayerConnected: ["lobbies", "set_player_connected"],
		setPlayerDisconnected: ["lobbies", "set_player_disconnected"],
		find: ["lobbies", "find"],
		forceGc: ["lobbies", "force_gc"],
		listRegions: ["lobbies", "list_regions"],
	},

	rivet: {
		call: ["rivet", "call"],
	},
} as const;
