// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-07-23T09:32:50.503Z

export type RequestOf<T> = T extends { request: any } ? T["request"] : never;
export type ResponseOf<T> = T extends { response: any } ? T["response"] : never;

export type DependencyCallFn<ThisType> = <
	M extends keyof DependenciesSnake & string,
	S extends keyof DependenciesSnake[M] & string,
>(
	this: ThisType,
	module: M,
	script: S,
	req: RequestOf<DependenciesSnake[M][S]>,
) => Promise<ResponseOf<DependenciesSnake[M][S]>>;

//
// Types for users
//

// modules.users.fetch
import type {
	Request as Users_Fetch_Req,
	Response as Users_Fetch_Res,
} from "../../opengb-modules/modules/users/scripts/fetch.ts";

// modules.users.create
import type {
	Request as Users_Create_Req,
	Response as Users_Create_Res,
} from "../../opengb-modules/modules/users/scripts/create.ts";

// modules.users.authenticateToken
import type {
	Request as Users_AuthenticateToken_Req,
	Response as Users_AuthenticateToken_Res,
} from "../../opengb-modules/modules/users/scripts/authenticate_token.ts";

// modules.users.createToken
import type {
	Request as Users_CreateToken_Req,
	Response as Users_CreateToken_Res,
} from "../../opengb-modules/modules/users/scripts/create_token.ts";

interface Users_Module {
	fetch: {
		request: Users_Fetch_Req;
		response: Users_Fetch_Res;
	};
	create: {
		request: Users_Create_Req;
		response: Users_Create_Res;
	};
	authenticate_token: {
		request: Users_AuthenticateToken_Req;
		response: Users_AuthenticateToken_Res;
	};
	create_token: {
		request: Users_CreateToken_Req;
		response: Users_CreateToken_Res;
	};
}

interface Users_ModuleCamel {
	fetch: {
		request: Users_Fetch_Req;
		response: Users_Fetch_Res;
	};
	create: {
		request: Users_Create_Req;
		response: Users_Create_Res;
	};
	authenticateToken: {
		request: Users_AuthenticateToken_Req;
		response: Users_AuthenticateToken_Res;
	};
	createToken: {
		request: Users_CreateToken_Req;
		response: Users_CreateToken_Res;
	};
}

//
// Types for rate_limit
//

// modules.rateLimit.throttle
import type {
	Request as RateLimit_Throttle_Req,
	Response as RateLimit_Throttle_Res,
} from "../../opengb-modules/modules/rate_limit/scripts/throttle.ts";

// modules.rateLimit.throttlePublic
import type {
	Request as RateLimit_ThrottlePublic_Req,
	Response as RateLimit_ThrottlePublic_Res,
} from "../../opengb-modules/modules/rate_limit/scripts/throttle_public.ts";

interface RateLimit_Module {
	throttle: {
		request: RateLimit_Throttle_Req;
		response: RateLimit_Throttle_Res;
	};
	throttle_public: {
		request: RateLimit_ThrottlePublic_Req;
		response: RateLimit_ThrottlePublic_Res;
	};
}

interface RateLimit_ModuleCamel {
	throttle: {
		request: RateLimit_Throttle_Req;
		response: RateLimit_Throttle_Res;
	};
	throttlePublic: {
		request: RateLimit_ThrottlePublic_Req;
		response: RateLimit_ThrottlePublic_Res;
	};
}

//
// Types for tokens
//

// modules.tokens.create
import type {
	Request as Tokens_Create_Req,
	Response as Tokens_Create_Res,
} from "../../opengb-modules/modules/tokens/scripts/create.ts";

// modules.tokens.fetch
import type {
	Request as Tokens_Fetch_Req,
	Response as Tokens_Fetch_Res,
} from "../../opengb-modules/modules/tokens/scripts/fetch.ts";

// modules.tokens.fetchByToken
import type {
	Request as Tokens_FetchByToken_Req,
	Response as Tokens_FetchByToken_Res,
} from "../../opengb-modules/modules/tokens/scripts/fetch_by_token.ts";

// modules.tokens.revoke
import type {
	Request as Tokens_Revoke_Req,
	Response as Tokens_Revoke_Res,
} from "../../opengb-modules/modules/tokens/scripts/revoke.ts";

// modules.tokens.validate
import type {
	Request as Tokens_Validate_Req,
	Response as Tokens_Validate_Res,
} from "../../opengb-modules/modules/tokens/scripts/validate.ts";

// modules.tokens.extend
import type {
	Request as Tokens_Extend_Req,
	Response as Tokens_Extend_Res,
} from "../../opengb-modules/modules/tokens/scripts/extend.ts";

interface Tokens_Module {
	create: {
		request: Tokens_Create_Req;
		response: Tokens_Create_Res;
	};
	fetch: {
		request: Tokens_Fetch_Req;
		response: Tokens_Fetch_Res;
	};
	fetch_by_token: {
		request: Tokens_FetchByToken_Req;
		response: Tokens_FetchByToken_Res;
	};
	revoke: {
		request: Tokens_Revoke_Req;
		response: Tokens_Revoke_Res;
	};
	validate: {
		request: Tokens_Validate_Req;
		response: Tokens_Validate_Res;
	};
	extend: {
		request: Tokens_Extend_Req;
		response: Tokens_Extend_Res;
	};
}

interface Tokens_ModuleCamel {
	create: {
		request: Tokens_Create_Req;
		response: Tokens_Create_Res;
	};
	fetch: {
		request: Tokens_Fetch_Req;
		response: Tokens_Fetch_Res;
	};
	fetchByToken: {
		request: Tokens_FetchByToken_Req;
		response: Tokens_FetchByToken_Res;
	};
	revoke: {
		request: Tokens_Revoke_Req;
		response: Tokens_Revoke_Res;
	};
	validate: {
		request: Tokens_Validate_Req;
		response: Tokens_Validate_Res;
	};
	extend: {
		request: Tokens_Extend_Req;
		response: Tokens_Extend_Res;
	};
}

//
// Types for lobbies
//

// modules.lobbies.create
import type {
	Request as Lobbies_Create_Req,
	Response as Lobbies_Create_Res,
} from "../../opengb-modules/modules/lobbies/scripts/create.ts";

// modules.lobbies.destroy
import type {
	Request as Lobbies_Destroy_Req,
	Response as Lobbies_Destroy_Res,
} from "../../opengb-modules/modules/lobbies/scripts/destroy.ts";

// modules.lobbies.findOrCreate
import type {
	Request as Lobbies_FindOrCreate_Req,
	Response as Lobbies_FindOrCreate_Res,
} from "../../opengb-modules/modules/lobbies/scripts/find_or_create.ts";

// modules.lobbies.join
import type {
	Request as Lobbies_Join_Req,
	Response as Lobbies_Join_Res,
} from "../../opengb-modules/modules/lobbies/scripts/join.ts";

// modules.lobbies.list
import type {
	Request as Lobbies_List_Req,
	Response as Lobbies_List_Res,
} from "../../opengb-modules/modules/lobbies/scripts/list.ts";

// modules.lobbies.setLobbyReady
import type {
	Request as Lobbies_SetLobbyReady_Req,
	Response as Lobbies_SetLobbyReady_Res,
} from "../../opengb-modules/modules/lobbies/scripts/set_lobby_ready.ts";

// modules.lobbies.setPlayerConnected
import type {
	Request as Lobbies_SetPlayerConnected_Req,
	Response as Lobbies_SetPlayerConnected_Res,
} from "../../opengb-modules/modules/lobbies/scripts/set_player_connected.ts";

// modules.lobbies.setPlayerDisconnected
import type {
	Request as Lobbies_SetPlayerDisconnected_Req,
	Response as Lobbies_SetPlayerDisconnected_Res,
} from "../../opengb-modules/modules/lobbies/scripts/set_player_disconnected.ts";

// modules.lobbies.find
import type {
	Request as Lobbies_Find_Req,
	Response as Lobbies_Find_Res,
} from "../../opengb-modules/modules/lobbies/scripts/find.ts";

// modules.lobbies.forceGc
import type {
	Request as Lobbies_ForceGc_Req,
	Response as Lobbies_ForceGc_Res,
} from "../../opengb-modules/modules/lobbies/scripts/force_gc.ts";

// modules.lobbies.listRegions
import type {
	Request as Lobbies_ListRegions_Req,
	Response as Lobbies_ListRegions_Res,
} from "../../opengb-modules/modules/lobbies/scripts/list_regions.ts";

interface Lobbies_Module {
	create: {
		request: Lobbies_Create_Req;
		response: Lobbies_Create_Res;
	};
	destroy: {
		request: Lobbies_Destroy_Req;
		response: Lobbies_Destroy_Res;
	};
	find_or_create: {
		request: Lobbies_FindOrCreate_Req;
		response: Lobbies_FindOrCreate_Res;
	};
	join: {
		request: Lobbies_Join_Req;
		response: Lobbies_Join_Res;
	};
	list: {
		request: Lobbies_List_Req;
		response: Lobbies_List_Res;
	};
	set_lobby_ready: {
		request: Lobbies_SetLobbyReady_Req;
		response: Lobbies_SetLobbyReady_Res;
	};
	set_player_connected: {
		request: Lobbies_SetPlayerConnected_Req;
		response: Lobbies_SetPlayerConnected_Res;
	};
	set_player_disconnected: {
		request: Lobbies_SetPlayerDisconnected_Req;
		response: Lobbies_SetPlayerDisconnected_Res;
	};
	find: {
		request: Lobbies_Find_Req;
		response: Lobbies_Find_Res;
	};
	force_gc: {
		request: Lobbies_ForceGc_Req;
		response: Lobbies_ForceGc_Res;
	};
	list_regions: {
		request: Lobbies_ListRegions_Req;
		response: Lobbies_ListRegions_Res;
	};
}

interface Lobbies_ModuleCamel {
	create: {
		request: Lobbies_Create_Req;
		response: Lobbies_Create_Res;
	};
	destroy: {
		request: Lobbies_Destroy_Req;
		response: Lobbies_Destroy_Res;
	};
	findOrCreate: {
		request: Lobbies_FindOrCreate_Req;
		response: Lobbies_FindOrCreate_Res;
	};
	join: {
		request: Lobbies_Join_Req;
		response: Lobbies_Join_Res;
	};
	list: {
		request: Lobbies_List_Req;
		response: Lobbies_List_Res;
	};
	setLobbyReady: {
		request: Lobbies_SetLobbyReady_Req;
		response: Lobbies_SetLobbyReady_Res;
	};
	setPlayerConnected: {
		request: Lobbies_SetPlayerConnected_Req;
		response: Lobbies_SetPlayerConnected_Res;
	};
	setPlayerDisconnected: {
		request: Lobbies_SetPlayerDisconnected_Req;
		response: Lobbies_SetPlayerDisconnected_Res;
	};
	find: {
		request: Lobbies_Find_Req;
		response: Lobbies_Find_Res;
	};
	forceGc: {
		request: Lobbies_ForceGc_Req;
		response: Lobbies_ForceGc_Res;
	};
	listRegions: {
		request: Lobbies_ListRegions_Req;
		response: Lobbies_ListRegions_Res;
	};
}

//
// Types for rivet
//

// modules.rivet.call
import type {
	Request as Rivet_Call_Req,
	Response as Rivet_Call_Res,
} from "../../opengb-modules/modules/rivet/scripts/call.ts";

interface Rivet_Module {
	call: {
		request: Rivet_Call_Req;
		response: Rivet_Call_Res;
	};
}

interface Rivet_ModuleCamel {
	call: {
		request: Rivet_Call_Req;
		response: Rivet_Call_Res;
	};
}

interface DependenciesSnake {
	users: Users_Module;
	rate_limit: RateLimit_Module;
	tokens: Tokens_Module;
	lobbies: Lobbies_Module;
	rivet: Rivet_Module;
}

interface DependenciesCamel {
	users: Users_ModuleCamel;
	rateLimit: RateLimit_ModuleCamel;
	tokens: Tokens_ModuleCamel;
	lobbies: Lobbies_ModuleCamel;
	rivet: Rivet_ModuleCamel;
}
